import { Plant } from './types';

export const PLANTS: Plant[] = [
  {
    id: '1',
    name: 'Monstera Deliciosa',
    scientificName: 'Monstera deliciosa',
    description: "The 'Swiss Cheese Plant' is famous for its quirky natural leaf holes. A statement piece that grows with you.",
    category: 'indoor',
    difficulty: 'easy',
    sunlight: 'medium',
    water: 'medium',
    imageUrl: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=800&q=80', 
    tags: ['pet-toxic', 'air-purifier', 'statement'],
    availability: 'in-stock',
    size: '10-inch pot',
    location: 'Greenhouse A, Row 3',
    isNew: true
  },
  {
    id: '2',
    name: 'Fiddle Leaf Fig',
    scientificName: 'Ficus lyrata',
    description: "Known for its violin-shaped leaves, the Fiddle Leaf Fig is a modern classic. It loves bright, indirect light and stability.",
    category: 'indoor',
    difficulty: 'moderate',
    sunlight: 'high',
    water: 'medium',
    imageUrl: 'https://images.unsplash.com/photo-1612474751765-1d07ec0176d6?auto=format&fit=crop&w=800&q=80',
    tags: ['tall', 'structural', 'popular'],
    availability: 'low-stock',
    size: '3ft tall / 12-inch pot',
    location: 'Greenhouse A, Entrance'
  },
  {
    id: '3',
    name: 'Snake Plant',
    scientificName: 'Sansevieria trifasciata',
    description: "Indestructible and architectural. The Snake Plant thrives on neglect and low light, making it perfect for beginners.",
    category: 'succulent',
    difficulty: 'easy',
    sunlight: 'low',
    water: 'low',
    imageUrl: 'https://images.unsplash.com/photo-1598544456955-49298715874c?auto=format&fit=crop&w=800&q=80',
    tags: ['low-light', 'air-purifier', 'drought-tolerant'],
    availability: 'in-stock',
    size: '6-inch pot',
    location: 'Succulent House'
  },
  {
    id: '4',
    name: 'Peace Lily',
    scientificName: 'Spathiphyllum',
    description: "Elegant white blooms rise from dark green foliage. It tells you when it's thirsty by gently drooping.",
    category: 'flowering',
    difficulty: 'easy',
    sunlight: 'low',
    water: 'high',
    imageUrl: 'https://images.unsplash.com/photo-1593691509543-c55ce1407012?auto=format&fit=crop&w=800&q=80',
    tags: ['flowering', 'air-purifier', 'communicative'],
    availability: 'out-of-stock',
    size: '8-inch pot',
    location: 'Shade House'
  },
  {
    id: '5',
    name: 'Rubber Plant',
    scientificName: 'Ficus elastica',
    description: "Glossy, dark burgundy leaves that add drama to any corner. Keep the leaves dusted to let them shine.",
    category: 'indoor',
    difficulty: 'easy',
    sunlight: 'medium',
    water: 'medium',
    imageUrl: 'https://images.unsplash.com/photo-1610499696885-303c26027a44?auto=format&fit=crop&w=800&q=80',
    tags: ['glossy', 'burgundy', 'sturdy'],
    availability: 'in-stock',
    size: '2ft tall',
    location: 'Greenhouse B',
    isNew: true
  },
  {
    id: '6',
    name: 'String of Pearls',
    scientificName: 'Senecio rowleyanus',
    description: "Cascading beads of green that look stunning in a hanging basket. Needs bright light to keep the pearls plump.",
    category: 'succulent',
    difficulty: 'moderate',
    sunlight: 'high',
    water: 'low',
    imageUrl: 'https://images.unsplash.com/photo-1622375836248-0382905273f7?auto=format&fit=crop&w=800&q=80',
    tags: ['hanging', 'unique', 'fast-growing'],
    availability: 'seasonal',
    size: '6-inch hanging basket',
    location: 'Succulent House, Hanging Racks'
  },
  {
    id: '7',
    name: 'Bird of Paradise',
    scientificName: 'Strelitzia nicolai',
    description: "Bring the tropics home. Large, banana-like leaves create a lush jungle feel. Requires plenty of space.",
    category: 'indoor',
    difficulty: 'moderate',
    sunlight: 'high',
    water: 'medium',
    imageUrl: 'https://images.unsplash.com/photo-1550952083-d90c74681691?auto=format&fit=crop&w=800&q=80',
    tags: ['tropical', 'large', 'statement'],
    availability: 'in-stock',
    size: '4ft tall / 5 gallon',
    location: 'Main Atrium'
  },
  {
    id: '8',
    name: 'Lavender',
    scientificName: 'Lavandula',
    description: "Fragrant and calming. Perfect for a sunny kitchen window or outdoor patio. Bees love it.",
    category: 'outdoor',
    difficulty: 'moderate',
    sunlight: 'high',
    water: 'low',
    imageUrl: 'https://images.unsplash.com/photo-1563212891-953e50697205?auto=format&fit=crop&w=800&q=80',
    tags: ['fragrant', 'outdoor', 'pollinator-friendly'],
    availability: 'seasonal',
    size: '1 gallon pot',
    location: 'Outdoor Nursery, Row 1'
  },
];